{
  # Import all your configuration modules here
  imports = [
    ./bufferline.nix
    ./pbcopy.nix
    ./colorscheme.nix
    ./keymaps.nix
    ./treesitter.nix
    ./snacks.nix
    ./trouble.nix
    ./blink.nix
    ./conform.nix
    ./lspconfig.nix
    ./which-key.nix
    ./git.nix
    ./icons.nix
    ./noice.nix
    ./airline.nix
    ./telescope.nix
    ./harpoon.nix
    ./oil.nix
    ./oil-git-status.nix
    ./dap.nix
    ./render-markdown.nix
    ./neotest.nix
    ./navbuddy.nix
    ./treesitter-context.nix
    ./lazygit.nix
    ./flash.nix
    ./mini.nix
    ./persistence.nix
    ./tmux-navigator.nix
    ./comment.nix
    ./sleuth.nix
    ./fidget.nix
    ./lazydev.nix
    ./editorconfig.nix
    ./supermaven.nix
    ./alpha.nix
    ./arrow.nix
    ./twilight.nix
  ];
}
